### ISSUE TITLE
Node Red docker crashed when Crate node is down

### ISSUE THREAD

**Issue by rjbaat** [okeeffe/node-red-contrib-crate#3]
Hi,
I have a problem with the crate node in Node Red. I have it running in docker and connected to a crate db in a cluster.
But when the crateDB node in the cluster is down and not accessible the Node Red docker crashed with this error log:

```
18 May 07:14:29 - Error: connect ECONNREFUSED 192.168.235.9:4200
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1105:14)

npm ERR! Linux 4.4.0-109-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start" "--" "--userDir" "/data"
npm ERR! node v6.13.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! node-red-docker@1.0.0 start: `node $NODE_OPTIONS node_modules/node-red/red.js -v $FLOWS "--userDir" "/data"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-red-docker@1.0.0 start script 'node $NODE_OPTIONS node_modules/node-red/red.js -v $FLOWS "--userDir" "/data"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-red-docker package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node $NODE_OPTIONS node_modules/node-red/red.js -v $FLOWS "--userDir" "/data"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-red-docker
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-red-docker
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/src/node-red/npm-debug.log
[..................] \ : verb config Skipping project config: /usr/src/node-red


> node-red-docker@1.0.0 start /usr/src/node-red
> node $NODE_OPTIONS node_modules/node-red/red.js -v $FLOWS "--userDir" "/data"
```

**Comment by okeeffe** [comment]
Hi @rjbaat!

Looking at the code, it seems I didn't handle a case where the `db.connect` attempts fail. Do you want to take a crack at handling that exception and open a PR?

And just to make totally sure, this crash doesn't happen if the crate node isn't in your flow?

**Comment by rjbaat** [comment]
Hi @okeeffe, 
I think your right. Its only crashing when it cant connect. Since iam not really a programmer i cant fix this issue unfortunately :(. 

Yes, well i had only 1 little flow on the docker instance with only your node and in MQTT input. So iam almost certain that the disconnected node would cause the crash. Because i tired it a couple of times and put the Crate instance down and indeed it was resulting in this crash.

**Comment by rjbaat** [comment]
I have some more logging info:
```
21 Jun 14:35:28 - [red] Uncaught Exception:
21 Jun 14:35:28 - Error: connect ECONNREFUSED 192.168.235.10:4201
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1105:14)
---------------------------------------------
    at Socket.Readable.on (_stream_readable.js:687:35)
    at tickOnSocket (_http_client.js:560:10)
    at onSocketNT (_http_client.js:590:5)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
---------------------------------------------
    at ClientRequest.onSocket (_http_client.js:578:11)
    at _http_agent.js:159:11
    at oncreate (_http_agent.js:200:5)
    at Agent.createSocket (_http_agent.js:187:5)
    at Agent.addRequest (_http_agent.js:152:10)
    at new ClientRequest (_http_client.js:160:16)
    at Object.exports.request (http.js:31:10)
    at getRequest (/data/node_modules/node-crate/lib/connection-pool.js:41:15)
    at Object.getSqlRequest (/data/node_modules/node-crate/lib/connection-pool.js:76:12)

npm ERR! Linux 4.9.87-linuxkit-aufs
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start" "--" "--userDir" "/data"
npm ERR! node v6.13.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! node-red-docker@1.0.0 start: `node $NODE_OPTIONS node_modules/node-red/red.js -v $FLOWS "--userDir" "/data"`
npm ERR! Exit status 1

 
npm ERR! Failed at the node-red-docker@1.0.0 start script 'node $NODE_OPTIONS node_modules/node-red/red.js -v $FLOWS "--userDir" "/data"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-red-docker package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node $NODE_OPTIONS node_modules/node-red/red.js -v $FLOWS "--userDir" "/data"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-red-docker
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-red-docker
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/src/node-red/npm-debug.log
```
